measuredlaunch: rework ml-functions for tpm2 reseal
This updates the ml-fuctions to work with the new pcr-calc for forward
seal on TPM2.0 and TPM1.2 with DA policy.

OXT-1004

Signed-off-by: Daniel P. Smith <dpsmith@apertussolutions.com>

diff --git a/recipes-openxt/openxt/openxt-measuredlaunch/seal-system b/recipes-openxt/openxt/openxt-measuredlaunch/seal-system
--- a/recipes-openxt/openxt/openxt-measuredlaunch/seal-system
+++ b/recipes-openxt/openxt/openxt-measuredlaunch/seal-system
@@ -33,13 +33,21 @@ tpm2=$?
 operation="seal"
 config_key="/config/keys/config.key"
 sealed_key="/boot/system/tpm/config.tss"
-pcr_list="/config/config.pcrs"
+static_pcrs="0 1 2 3"
+dynamic_pcrs="15 17 18 19"
+hashalg="sha1"
 good_pcrs="/config/good.pcrs"
 bad_pcrs="/boot/system/tpm/bad.pcrs"
 root_dev="/dev/mapper/xenclient-root"
 
-while getopts ":fc:t:p:g:b:r:" opt; do
+while getopts ":sufc:t:p:g:b:r:" opt; do
     case $opt in
+    s)
+        operation="seal"
+    ;;
+    u)
+        operation="unseal"
+    ;;
     f)
         operation="forward"
     ;;
@@ -67,45 +75,24 @@ while getopts ":fc:t:p:g:b:r:" opt; do
     esac
 done
 
+[ "${tpm2}" -eq 0 ] && hashalg=$(get_preferred_alg)
 
 case $operation in
 seal)
-    local file_exists=1
-    if [ "${tpm2}" -eq 0 ];
-    then
-        sealerr=0
-        seal_file=${config_key}
-        clean_old_tpm_files
-        if pcr_bank_exists "TPM_ALG_SHA1"; then
-            sealout=$(tpm2_sealdata -H 0x81000001 -I ${seal_file} -O ${sealed_key}.sha1 -o ${sealed_key}.pub.sha1 -g 0x4 -G 8 -b 0x492 $(cat /config/config.pcrs) 2>&1)
-            sealerr=$?
-        fi
-        if pcr_bank_exists "TPM_ALG_SHA256" && [ ${sealerr} -eq 0 ]; then
-            sealout=$(tpm2_sealdata -H 0x81000000 -I ${seal_file} -O ${sealed_key}.sha256 -o ${sealed_key}.pub.sha256 -g 0xB -G 8 -b 0x492 $(cat /config/config.pcrs) 2>&1)
-            sealerr=$?
-        fi
-    else
-        sealout=$(tpm_sealdata_sa -i ${config_key} \
-            -o ${sealed_key} -z $(cat ${pcr_list}) 2>&1)
-        sealerr=$?
-    fi
+    clean_old_tpm_files
 
-    if [ -e ${sealed_key} ]; then
-        file_exists=0
-    elif [ -e ${sealed_key}.sha1 ]; then
-        file_exists=0
-    elif [ -e ${sealed_key}.sha256 ]; then
-        file_exists=0
-    else
-        file_exists=1
-    fi
+    for p in ${static_pcrs} ${dynamic_pcrs}; do
+        pcr_params="${pcr_params} -p ${p}"
+    done
 
-    if [ $sealerr -eq 0 ] && [ $file_exists -eq 0 ]; then
+    tpm_seal -a ${hashalg} ${pcr_params} ${config_key} ${sealed_key}
+    sealerr=$?
+
+    if [ $sealerr -eq 0 ] && [ -e ${sealed_key} ]; then
         # store PCR hints for recovery
         if [ -d "${TPM_DEV}" ]; then
             [ -f "${bad_pcrs}" ] && rm "${bad_pcrs}"
-            if [ "${tpm2}" -eq 0 ];
-            then
+            if [ "${tpm2}" -eq 0 ]; then
                 tpm2_listpcrs > "${good_pcrs}"
             else
                 cat "${TPM_DEV}/pcrs" > "${good_pcrs}"
@@ -116,41 +103,53 @@ seal)
     fi
 ;;
 forward)
+    # This is to support upgrade from previous releases that did not have to
+    # identify hash algorithm in use.
+    [[ -e "${sealed_key}" ]] && mv ${sealed_key} ${sealed_key}.${hashalg}
 
-    pcrs=$(calculate_pcrs "/" /boot/system/grub/grub.cfg) ||
+    for p in ${static_pcrs}; do
+        pcr_params="${pcr_params} -p ${p}"
+    done
+
+    # During early init, rootfs is hashed and is given to
+    # tpm_extend which hashes the rootfs hash and hands that value
+    # to the TPM to be extended into PCR 15
+    root_hash=$(${hashalg}sum ${root_dev}|cut -f1 -d' ')
+    pcr15=$(hash_extend 0 \
+            $(echo -n ${root_hash}|${hashalg}sum|cut -f1 -d' ') \
+            ${hashalg}) ||
+        err "failed to hash root device"
+
+    pcr_params="${pcr_params} -p 15:${pcr15}"
+
+    pcrs=$(calculate_pcrs "/" /boot/system/grub/grub.cfg ${hashalg}) ||
         err "failed to calculate pcrs"
 
     pcr17=$(echo $pcrs | awk '{ print $1 }')
     pcr18=$(echo $pcrs | awk '{ print $2 }')
     pcr19=$(echo $pcrs | awk '{ print $3 }')
 
-    if [ "${tpm2}" -eq 0 ]; then
-        shaalg="sha256sum"
-    else
-        shaalg="sha1sum"
-    fi
-    # During early init, rootfs is hashed and is given to
-    # tpm_extend which hashes the rootfs hash and hands that value
-    # to the TPM to be extended into PCR 15
-    root_hash=$(${shaalg} ${root_dev}|cut -f1 -d' ')
-    pcr15=$(hash_extend 0 $(echo -n ${root_hash}|${shaalg}|cut -f1 -d' ')) ||
-        err "failed to hash root device"
+    pcr_params="${pcr_params} -p 17:${pcr17} -p 18:${pcr18} -p 19:${pcr19}"
 
-    if [ -e "${sealed_key}" ]; then
-        mv ${sealed_key} ${sealed_key}.old
-    fi
-    if [ -e "${sealed_key}.sha1" ]; then
-        mv ${sealed_key}.sha1 ${sealed_key}.sha1.old
-    fi
-    if [ -e "${sealed_key}.sha256" ]; then
-        mv ${sealed_key}.sha256 ${sealed_key}.sha256.old
-    fi
+    [[ -e "${sealed_key}.pub.${hashalg}" ]] && rm -f ${sealed_key}.pub.${hashalg}
+    mv ${sealed_key}.${hashalg} ${sealed_key}.${hashalg}.old
 
-    tpm_forward_seal -r/ -p15:${pcr15} -p17:${pcr17} -p18:${pcr18} \
-        -p19:${pcr19} ${config_key} ${sealed_key}
+    tpm_forward_seal -a ${hashalg} ${pcr_params} ${config_key} ${sealed_key}
     [ $? -eq 0 ] || err "forward seal of key failed"
 
     exit 0
+;;
+unseal)
+    for p in ${static_pcrs} ${dynamic_pcrs}; do
+        pcr_params="${pcr_params} -p ${p}"
+    done
+
+    [ -e "${sealed_key}.${hashalg}" ] || err "sealed key file missing"
+    [ "${tpm2}" -eq 0 ] && [ -e "${sealed_key}.pub.${hashalg}" ] ||
+        err "sealed pub key file missing"
+
+    tpm_unseal -a ${hashalg} ${pcr_params} ${sealed_key}
+    [ $? -eq 0 ] || err "unseal failed"
 ;;
 esac
 
